create table if not exists public.price_list_items (
    id bigint generated by default as identity primary key,
    source_product_id bigint unique references public.products(id) on delete set null,
    code text,
    name text not null,
    spec text,
    unit text not null default 'EA',
    manufacturer text,
    price numeric(18, 4) not null default 0 check (price >= 0),
    currency text not null default 'KRW' check (currency in ('KRW', 'USD', 'CNY', 'JPY', 'EUR', 'GBP')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

insert into public.price_list_items (
    source_product_id,
    code,
    name,
    spec,
    unit,
    manufacturer
)
select
    p.id,
    p.code,
    p.name,
    p.spec,
    coalesce(nullif(p.unit, ''), 'EA'),
    p.manufacturer
from public.products p
on conflict (source_product_id) do nothing;

create or replace function public.add_product_to_price_list()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
    insert into public.price_list_items (
        source_product_id,
        code,
        name,
        spec,
        unit,
        manufacturer
    )
    values (
        new.id,
        new.code,
        new.name,
        new.spec,
        coalesce(nullif(new.unit, ''), 'EA'),
        new.manufacturer
    )
    on conflict (source_product_id) do nothing;

    return new;
end;
$$;

drop trigger if exists products_add_to_price_list on public.products;
create trigger products_add_to_price_list
after insert on public.products
for each row
execute function public.add_product_to_price_list();

alter table public.price_list_items enable row level security;

drop policy if exists "Authenticated users can manage price list" on public.price_list_items;
create policy "Authenticated users can manage price list"
    on public.price_list_items
    for all
    to authenticated
    using (true)
    with check (true);

grant select, insert, update, delete on public.price_list_items to authenticated;
grant usage, select on sequence public.price_list_items_id_seq to authenticated;

notify pgrst, 'reload schema';
