create table if not exists public.memo_folders (
    id bigint generated by default as identity primary key,
    name text not null unique check (char_length(trim(name)) between 1 and 50),
    created_at timestamptz not null default now()
);

alter table public.memos
    add column if not exists folder_id bigint references public.memo_folders(id) on delete set null;

create index if not exists memos_folder_id_idx on public.memos(folder_id);

alter table public.memo_folders enable row level security;

drop policy if exists "Authenticated users can read memo folders" on public.memo_folders;
create policy "Authenticated users can read memo folders"
    on public.memo_folders for select
    to authenticated
    using (true);

drop policy if exists "Authenticated users can create memo folders" on public.memo_folders;
create policy "Authenticated users can create memo folders"
    on public.memo_folders for insert
    to authenticated
    with check (true);

drop policy if exists "Authenticated users can update memo folders" on public.memo_folders;
create policy "Authenticated users can update memo folders"
    on public.memo_folders for update
    to authenticated
    using (true)
    with check (true);

drop policy if exists "Authenticated users can delete memo folders" on public.memo_folders;
create policy "Authenticated users can delete memo folders"
    on public.memo_folders for delete
    to authenticated
    using (true);

grant select, insert, update, delete on public.memo_folders to authenticated;
grant usage, select on sequence public.memo_folders_id_seq to authenticated;

notify pgrst, 'reload schema';
