create table public.rentals (
    id bigint generated by default as identity primary key,
    rental_no text not null unique,
    rental_date date not null default current_date,
    partner_id bigint,
    partner_name text not null,
    partner_address text,
    contact_name text,
    contact_phone text,
    expected_return_date date not null,
    actual_return_date date,
    rental_purpose text not null default 'test',
    rental_purpose_detail text,
    project_name text,
    status text not null default 'on_loan',
    memo text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint rentals_partner_id_fkey
        foreign key (partner_id) references public.partners(id) on delete restrict,
    constraint rentals_purpose_check
        check (rental_purpose in ('test', 'demo', 'temporary_replacement', 'project', 'other')),
    constraint rentals_status_check
        check (status in ('on_loan', 'return_due', 'returned', 'long_term')),
    constraint rentals_expected_date_check
        check (expected_return_date >= rental_date),
    constraint rentals_actual_date_check
        check (actual_return_date is null or actual_return_date >= rental_date)
);

create table public.rental_items (
    id bigint generated by default as identity primary key,
    rental_id bigint not null,
    display_order integer not null default 0,
    product_id bigint,
    item_name text not null,
    model_name text,
    manufacturer text,
    serial_number text,
    asset_number text,
    quantity integer not null default 1,
    returned_quantity integer not null default 0,
    unit text not null default 'EA',
    return_date date,
    item_status text not null default 'normal',
    memo text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint rental_items_rental_id_fkey
        foreign key (rental_id) references public.rentals(id) on delete cascade,
    constraint rental_items_product_id_fkey
        foreign key (product_id) references public.products(id) on delete set null,
    constraint rental_items_quantity_check
        check (quantity > 0),
    constraint rental_items_returned_quantity_check
        check (returned_quantity >= 0 and returned_quantity <= quantity),
    constraint rental_items_return_date_check
        check ((returned_quantity = 0 and return_date is null) or (returned_quantity > 0 and return_date is not null)),
    constraint rental_items_status_check
        check (item_status in ('normal', 'damaged', 'lost', 'repair_needed', 'other'))
);

create index rentals_rental_date_idx on public.rentals (rental_date desc, created_at desc);
create index rentals_expected_status_idx on public.rentals (expected_return_date, status);
create index rentals_partner_id_idx on public.rentals (partner_id);
create index rental_items_rental_order_idx on public.rental_items (rental_id, display_order);
create index rental_items_product_id_idx on public.rental_items (product_id);
create index rental_items_item_name_idx on public.rental_items (item_name);

create or replace function public.touch_rental_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

create trigger rentals_touch_updated_at
before update on public.rentals
for each row execute function public.touch_rental_updated_at();

create trigger rental_items_touch_updated_at
before update on public.rental_items
for each row execute function public.touch_rental_updated_at();

create or replace function public.save_rental(
    p_rental jsonb,
    p_items jsonb,
    p_rental_id bigint default null
)
returns bigint
language plpgsql
security invoker
set search_path = ''
as $$
declare
    v_rental_id bigint;
    v_rental_no text;
    v_rental_date date;
    v_expected_return_date date;
    v_actual_return_date date;
    v_partner_id bigint;
    v_partner_name text;
    v_registered_partner_name text;
    v_status text;
    v_item jsonb;
    v_item_count integer;
    v_quantity integer;
    v_returned_quantity integer;
    v_return_date date;
    v_remaining integer;
    v_last_return_date date;
    v_sequence integer;
begin
    if (select auth.uid()) is null then
        raise exception '로그인이 필요합니다.' using errcode = '42501';
    end if;

    v_rental_date := nullif(p_rental ->> 'rental_date', '')::date;
    v_expected_return_date := nullif(p_rental ->> 'expected_return_date', '')::date;
    v_actual_return_date := nullif(p_rental ->> 'actual_return_date', '')::date;
    v_partner_id := nullif(p_rental ->> 'partner_id', '')::bigint;
    v_partner_name := nullif(trim(p_rental ->> 'partner_name'), '');
    v_status := coalesce(nullif(p_rental ->> 'status', ''), 'on_loan');

    if v_rental_date is null or v_expected_return_date is null or v_partner_name is null then
        raise exception '대여일자, 거래처, 회수예정일은 필수입니다.' using errcode = '22023';
    end if;
    if v_expected_return_date < v_rental_date then
        raise exception '회수예정일은 대여일자보다 빠를 수 없습니다.' using errcode = '22023';
    end if;
    if v_actual_return_date is not null and v_actual_return_date < v_rental_date then
        raise exception '실제 회수일은 대여일자보다 빠를 수 없습니다.' using errcode = '22023';
    end if;
    if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
        raise exception '대여 품목을 한 개 이상 입력해 주세요.' using errcode = '22023';
    end if;

    if v_partner_id is not null then
        select name into v_registered_partner_name
        from public.partners
        where id = v_partner_id;
        if v_registered_partner_name is null then
            raise exception '선택한 거래처를 찾을 수 없습니다.' using errcode = '23503';
        end if;
    end if;

    for v_item in select value from jsonb_array_elements(p_items)
    loop
        v_quantity := nullif(v_item ->> 'quantity', '')::integer;
        v_returned_quantity := coalesce(nullif(v_item ->> 'returned_quantity', '')::integer, 0);
        v_return_date := nullif(v_item ->> 'return_date', '')::date;

        if trim(coalesce(v_item ->> 'item_name', '')) = '' then
            raise exception '모든 대여 품목의 품목명을 입력해 주세요.' using errcode = '22023';
        end if;
        if v_quantity is null or v_quantity <= 0 then
            raise exception '대여수량은 1 이상의 정수여야 합니다.' using errcode = '22023';
        end if;
        if v_returned_quantity < 0 or v_returned_quantity > v_quantity then
            raise exception '회수수량은 0 이상이며 대여수량을 초과할 수 없습니다.' using errcode = '22023';
        end if;
        if (v_returned_quantity = 0 and v_return_date is not null)
            or (v_returned_quantity > 0 and v_return_date is null) then
            raise exception '회수수량과 품목별 회수일을 함께 입력해 주세요.' using errcode = '22023';
        end if;
        if v_return_date is not null and v_return_date < v_rental_date then
            raise exception '품목별 회수일은 대여일자보다 빠를 수 없습니다.' using errcode = '22023';
        end if;
    end loop;

    if p_rental_id is null then
        perform pg_advisory_xact_lock(hashtext('rentals:' || v_rental_date::text));

        select coalesce(max((regexp_match(rental_no, '-R([0-9]+)$'))[1]::integer), 0) + 1
        into v_sequence
        from public.rentals
        where rental_date = v_rental_date;

        v_rental_no := 'ASPEC-' || to_char(v_rental_date, 'YYMMDD') || '-R' || lpad(v_sequence::text, 2, '0');

        insert into public.rentals (
            rental_no, rental_date, partner_id, partner_name, partner_address, contact_name, contact_phone,
            expected_return_date, actual_return_date, rental_purpose,
            rental_purpose_detail, project_name, status, memo
        ) values (
            v_rental_no,
            v_rental_date,
            v_partner_id,
            v_partner_name,
            nullif(trim(p_rental ->> 'partner_address'), ''),
            nullif(trim(p_rental ->> 'contact_name'), ''),
            nullif(trim(p_rental ->> 'contact_phone'), ''),
            v_expected_return_date,
            v_actual_return_date,
            coalesce(nullif(p_rental ->> 'rental_purpose', ''), 'test'),
            nullif(trim(p_rental ->> 'rental_purpose_detail'), ''),
            nullif(trim(p_rental ->> 'project_name'), ''),
            v_status,
            nullif(trim(p_rental ->> 'memo'), '')
        ) returning id into v_rental_id;
    else
        update public.rentals
        set rental_date = v_rental_date,
            partner_id = v_partner_id,
            partner_name = v_partner_name,
            partner_address = nullif(trim(p_rental ->> 'partner_address'), ''),
            contact_name = nullif(trim(p_rental ->> 'contact_name'), ''),
            contact_phone = nullif(trim(p_rental ->> 'contact_phone'), ''),
            expected_return_date = v_expected_return_date,
            actual_return_date = v_actual_return_date,
            rental_purpose = coalesce(nullif(p_rental ->> 'rental_purpose', ''), 'test'),
            rental_purpose_detail = nullif(trim(p_rental ->> 'rental_purpose_detail'), ''),
            project_name = nullif(trim(p_rental ->> 'project_name'), ''),
            status = v_status,
            memo = nullif(trim(p_rental ->> 'memo'), '')
        where id = p_rental_id
        returning id into v_rental_id;

        if v_rental_id is null then
            raise exception '수정할 대여 건을 찾을 수 없습니다.' using errcode = 'P0002';
        end if;

        delete from public.rental_items where rental_id = v_rental_id;
    end if;

    insert into public.rental_items (
        rental_id, display_order, product_id, item_name, model_name, manufacturer,
        serial_number, asset_number, quantity, returned_quantity, unit,
        return_date, item_status, memo
    )
    select
        v_rental_id,
        ordinality::integer - 1,
        nullif(item ->> 'product_id', '')::bigint,
        trim(item ->> 'item_name'),
        nullif(trim(item ->> 'model_name'), ''),
        nullif(trim(item ->> 'manufacturer'), ''),
        nullif(trim(item ->> 'serial_number'), ''),
        nullif(trim(item ->> 'asset_number'), ''),
        (item ->> 'quantity')::integer,
        coalesce(nullif(item ->> 'returned_quantity', '')::integer, 0),
        coalesce(nullif(trim(item ->> 'unit'), ''), 'EA'),
        nullif(item ->> 'return_date', '')::date,
        coalesce(nullif(item ->> 'item_status', ''), 'normal'),
        nullif(trim(item ->> 'memo'), '')
    from jsonb_array_elements(p_items) with ordinality as items(item, ordinality);

    select
        coalesce(sum(quantity - returned_quantity), 0),
        max(return_date)
    into v_remaining, v_last_return_date
    from public.rental_items
    where rental_id = v_rental_id;

    if v_remaining = 0 then
        update public.rentals
        set status = 'returned',
            actual_return_date = coalesce(v_actual_return_date, v_last_return_date, current_date)
        where id = v_rental_id;
    elsif v_status = 'returned' or v_actual_return_date is not null then
        raise exception '미회수 품목이 남아 있어 회수완료 또는 실제 회수일을 지정할 수 없습니다.' using errcode = '22023';
    end if;

    return v_rental_id;
end;
$$;

alter table public.rentals enable row level security;
alter table public.rental_items enable row level security;

create policy "Authenticated users can manage rentals"
    on public.rentals for all to authenticated
    using (true) with check (true);

create policy "Authenticated users can manage rental items"
    on public.rental_items for all to authenticated
    using (true) with check (true);

revoke all on table public.rentals from anon;
revoke all on table public.rental_items from anon;
revoke all on sequence public.rentals_id_seq from anon;
revoke all on sequence public.rental_items_id_seq from anon;
revoke all on function public.save_rental(jsonb, jsonb, bigint) from public, anon;

grant select, insert, update, delete on table public.rentals to authenticated;
grant select, insert, update, delete on table public.rental_items to authenticated;
grant usage, select on sequence public.rentals_id_seq to authenticated;
grant usage, select on sequence public.rental_items_id_seq to authenticated;
grant execute on function public.save_rental(jsonb, jsonb, bigint) to authenticated;

notify pgrst, 'reload schema';
